<a href="https://colab.research.google.com/github/shohjahon1208/pythonjavoblar/blob/main/Numpy_massiv_reshape_Transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A=np.arange(6).reshape(3,2) #A massiv elementlari 0-6 gacha shape (3:2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
A.T # A massivi Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1,0) #A massivi Trasnpose korinishiga keltirish


array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
np.dot(A,A.T) #A va A taraspose ko'paytmasi

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])